[tool.black]
line-length = 100
target-version = ["py310"]

[tool.isort]
src_paths = [".", "src"]
profile = "black"
line_length = 100

[tool.mypy]
plugins = ["mypy_django_plugin.main"]
exclude = "apps/**/migrations/*.py"

[tool.django-stubs]
django_settings_module = "templateproject.settings"